### ISSUE TITLE
Issue with handling Carbon as Criterion value

### ISSUE THREAD

**Issue by VladimirBerdnik** [Saritasa/php-laravel-repositories#11]
https://github.com/Saritasa/php-laravel-repositories/blob/aa81d5cf40f840ce0e5cc956495bb3b77c60afe3/src/Repositories/Repository.php#L424

There is issue on this line. `whereDate()` performs casting of filtered column to date like `cast(created_at as date)` and this action drops time value of column and when we have time value in Carbon object not '00:00:00' it will give us wrong filtering results.

**Comment by veeeeeRySeXy** [comment]
I will check it out.

**Comment by veeeeeRySeXy** [comment]
Due to inactivity I close this issue
